Update Pomerium images to v0.15.6
pomerium/pomerium-helm pull request #225
Opened 2021-11-09 12:20 UTC by adamantal

## Summary
Updated tags of the Pomerium images to `v0.15.6` to incorporate the fix for [CVE-2021-41230](https://github.com/pomerium/pomerium/security/advisories/GHSA-j6wp-3859-vxfg).

## Related issues
The https://github.com/pomerium/pomerium/pull/2724 fix for the Pomerium helm chart

**Checklist**:
- [x] add related issues
- [x] update Configuration in README
- [x] update Changelog in README (major versions)
- [x] ready for review

2021-11-09 17:16 UTC, desimone approved these changes
Thanks @adamantal

2021-11-09 17:16 UTC, travisgroth requested changes
Hi @adamantal - Thanks!  Would you mind tweaking this to a patch?

2021-11-09 17:16 UTC, travisgroth commented on charts/pomerium/Chart.yaml
> +version: 25.1.0
```suggestion
version: 25.0.1
```

2021-11-10 10:49 UTC, adamantal commented
Changed the version to `25.0.1`.

2021-11-10 17:38 UTC, travisgroth approved these changes

2021-11-10 17:39 UTC, merged