upgrade Pomerium to v0.18
pomerium/pomerium-helm pull request #319
Opened 2022-07-28 19:26 UTC by wasaga

## Summary

Upgrades Pomerium to v0.18

## Related issues

**Checklist**:
- [ ] add related issues
- [ ] update Configuration in README
- [ ] update Changelog in README (major versions)
- [ ] update Upgrading in README (breaking changes)
- [x] ready for review

2022-07-28 19:32 UTC, calebdoxsey submitted a review, later dismissed

2022-07-29 00:53 UTC, desimone requested changes
Many of the markdown changes are whitespace / editor formatting. Can you either back out of those changes, or drop a config for whatever prettier/editor `rc` file so that we don't have future editor battles. Makes reviewing challening.

2022-07-29 00:53 UTC, desimone commented on charts/pomerium/README.md
> +    - [32.0.0]()
Please describe changes

2022-07-29 00:53 UTC, desimone commented on charts/pomerium/README.md
> +    - [32.0.0]()
Update link?

2022-07-29 00:53 UTC, desimone commented on charts/pomerium/templates/ingress-controller-deployment.yaml
> -          {{- if or .Values.config.insecure .Values.config.insecureProxy }}
Can you describe this change and add that description to the changelog?

2022-07-29 01:54 UTC, wasaga commented
Markdown is formatted with Prettier, similar to other repos. 
Repeating spaces were stripped automatically by it, there is no option to control that behaviour.

2022-07-29 03:02 UTC, desimone approved these changes

2022-07-29 12:18 UTC, merged